name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4.2.2

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag juniper/nita-ansible:$(cat VERSION.txt)

    - name: Log in to GitHub Container Registry
      if: github.event_name == 'push'
      uses: docker/login-action@v3.4.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push to GitHub Container Registry
      if: github.event_name == 'push'
      run: |
        VERSION=$(cat VERSION.txt)
        IMAGE=ghcr.io/${{ github.repository }}
        docker tag juniper/nita-ansible:${VERSION} ${IMAGE,,}:${VERSION}
        docker tag juniper/nita-ansible:${VERSION} ${IMAGE,,}:latest
        docker push ${IMAGE,,}:${VERSION}
        docker push ${IMAGE,,}:latest
